"""initial_schema

Revision ID: 7897a73b8b56
Revises: None
Create Date: 2026-07-30 23:46:06.184992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7897a73b8b56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_courses_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('access_scope', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_tenant_email', ['tenant_id', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('glossary_terms',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.String(length=2000), nullable=False),
    sa.Column('domain_category', sa.String(length=100), nullable=True),
    sa.Column('source_slide', sa.String(length=100), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.create_index('ix_glossary_course_term', ['course_id', 'term'], unique=True)
        batch_op.create_index(batch_op.f('ix_glossary_terms_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_glossary_terms_term'), ['term'], unique=False)

    op.create_table('lessons',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_course_id'), ['course_id'], unique=False)
        batch_op.create_index('ix_lessons_course_order', ['course_id', 'order_index'], unique=False)

    op.create_table('model_configurations',
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('deployment_mode', sa.String(length=50), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_env_var_name', sa.String(length=100), nullable=True),
    sa.Column('api_base_url', sa.String(length=500), nullable=True),
    sa.Column('zero_data_retention', sa.Boolean(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_configurations', schema=None) as batch_op:
        batch_op.create_index('ix_model_config_course_active', ['course_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_configurations_course_id'), ['course_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index('ix_chat_sessions_user_course', ['user_id', 'course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('learning_documents',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_documents_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_documents_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('retrieval_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_chat_messages_session_role', ['session_id', 'role'], unique=False)

    op.create_table('document_versions',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('changelog', sa.String(length=1000), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['learning_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index('ix_doc_version_doc_num', ['document_id', 'version_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_document_versions_document_id'), ['document_id'], unique=False)

    op.create_table('content_blocks',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('block_type', sa.String(length=50), nullable=False),
    sa.Column('raw_content', sa.String(length=10000), nullable=False),
    sa.Column('normalized_content', sa.String(length=10000), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['learning_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_blocks', schema=None) as batch_op:
        batch_op.create_index('ix_blocks_docver_seq', ['document_version_id', 'sequence_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_blocks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_blocks_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_blocks_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('content_chunks',
    sa.Column('document_version_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.String(length=10000), nullable=False),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('has_formulas', sa.Boolean(), nullable=False),
    sa.Column('has_code', sa.Boolean(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunks_docver_index', ['document_version_id', 'chunk_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_chunks_document_version_id'), ['document_version_id'], unique=False)

    op.create_table('mindmaps',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('document_version_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('root_node_stable_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mindmaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mindmaps_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mindmaps_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mindmaps_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_completed_step', sa.String(length=100), nullable=True),
    sa.Column('checkpoint_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_course_status', ['course_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_status'), ['status'], unique=False)

    op.create_table('flashcards',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('content_chunk_id', sa.String(length=36), nullable=True),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('answer', sa.String(length=2000), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_chunk_id'], ['content_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcards_content_chunk_id'), ['content_chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcards_course_id'), ['course_id'], unique=False)
        batch_op.create_index('ix_flashcards_course_lesson', ['course_id', 'lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcards_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('mindmap_nodes',
    sa.Column('mindmap_id', sa.String(length=36), nullable=False),
    sa.Column('node_stable_id', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('parent_node_id', sa.String(length=36), nullable=True),
    sa.Column('slide_reference', sa.String(length=100), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mindmap_id'], ['mindmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_node_id'], ['mindmap_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mindmap_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mindmap_nodes_mindmap_id'), ['mindmap_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mindmap_nodes_node_stable_id'), ['node_stable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mindmap_nodes_parent_node_id'), ['parent_node_id'], unique=False)
        batch_op.create_index('ix_nodes_mindmap_stable', ['mindmap_id', 'node_stable_id'], unique=False)
        batch_op.create_index('ix_nodes_parent_order', ['parent_node_id', 'order_index'], unique=False)

    op.create_table('processing_tasks',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_result', sa.JSON(), nullable=True),
    sa.Column('error_details', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_tasks_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_tasks_job_order', ['job_id', 'step_order'], unique=False)

    op.create_table('source_references',
    sa.Column('chat_message_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('document_version_id', sa.String(length=36), nullable=True),
    sa.Column('content_chunk_id', sa.String(length=36), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('snippet_text', sa.String(length=2000), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_chunk_id'], ['content_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['learning_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_references_chat_message_id'), ['chat_message_id'], unique=False)
        batch_op.create_index('ix_source_refs_msg_doc', ['chat_message_id', 'document_id'], unique=False)

    op.create_table('flashcard_attempts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('flashcard_id', sa.String(length=36), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('selected_option', sa.String(length=500), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcard_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_attempts_user_card', ['user_id', 'flashcard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_attempts_flashcard_id'), ['flashcard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('learning_progress',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('mindmap_node_id', sa.String(length=36), nullable=True),
    sa.Column('completed_flashcards_count', sa.Integer(), nullable=False),
    sa.Column('total_flashcards_count', sa.Integer(), nullable=False),
    sa.Column('mastery_percentage', sa.Float(), nullable=False),
    sa.Column('last_studied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mindmap_node_id'], ['mindmap_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_progress_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_mindmap_node_id'), ['mindmap_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_progress_user_course', ['user_id', 'course_id'], unique=False)
        batch_op.create_index('ix_progress_user_lesson', ['user_id', 'lesson_id'], unique=False)

    op.create_table('node_flashcards',
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('flashcard_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['mindmap_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', 'flashcard_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_flashcards')
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_progress_user_lesson')
        batch_op.drop_index('ix_progress_user_course')
        batch_op.drop_index(batch_op.f('ix_learning_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_mindmap_node_id'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_course_id'))

    op.drop_table('learning_progress')
    with op.batch_alter_table('flashcard_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcard_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_flashcard_attempts_flashcard_id'))
        batch_op.drop_index('ix_attempts_user_card')

    op.drop_table('flashcard_attempts')
    with op.batch_alter_table('source_references', schema=None) as batch_op:
        batch_op.drop_index('ix_source_refs_msg_doc')
        batch_op.drop_index(batch_op.f('ix_source_references_chat_message_id'))

    op.drop_table('source_references')
    with op.batch_alter_table('processing_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_job_order')
        batch_op.drop_index(batch_op.f('ix_processing_tasks_job_id'))

    op.drop_table('processing_tasks')
    with op.batch_alter_table('mindmap_nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_nodes_parent_order')
        batch_op.drop_index('ix_nodes_mindmap_stable')
        batch_op.drop_index(batch_op.f('ix_mindmap_nodes_parent_node_id'))
        batch_op.drop_index(batch_op.f('ix_mindmap_nodes_node_stable_id'))
        batch_op.drop_index(batch_op.f('ix_mindmap_nodes_mindmap_id'))

    op.drop_table('mindmap_nodes')
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcards_lesson_id'))
        batch_op.drop_index('ix_flashcards_course_lesson')
        batch_op.drop_index(batch_op.f('ix_flashcards_course_id'))
        batch_op.drop_index(batch_op.f('ix_flashcards_content_chunk_id'))

    op.drop_table('flashcards')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_document_version_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_course_id'))
        batch_op.drop_index('ix_jobs_course_status')

    op.drop_table('processing_jobs')
    with op.batch_alter_table('mindmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mindmaps_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_mindmaps_document_version_id'))
        batch_op.drop_index(batch_op.f('ix_mindmaps_course_id'))

    op.drop_table('mindmaps')
    with op.batch_alter_table('content_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_chunks_document_version_id'))
        batch_op.drop_index('ix_chunks_docver_index')

    op.drop_table('content_chunks')
    with op.batch_alter_table('content_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_blocks_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_content_blocks_document_version_id'))
        batch_op.drop_index(batch_op.f('ix_content_blocks_document_id'))
        batch_op.drop_index('ix_blocks_docver_seq')

    op.drop_table('content_blocks')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_document_id'))
        batch_op.drop_index('ix_doc_version_doc_num')

    op.drop_table('document_versions')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_session_role')
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('learning_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_documents_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_learning_documents_course_id'))

    op.drop_table('learning_documents')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index('ix_chat_sessions_user_course')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_course_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('model_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_configurations_course_id'))
        batch_op.drop_index('ix_model_config_course_active')

    op.drop_table('model_configurations')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index('ix_lessons_course_order')
        batch_op.drop_index(batch_op.f('ix_lessons_course_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glossary_terms_term'))
        batch_op.drop_index(batch_op.f('ix_glossary_terms_course_id'))
        batch_op.drop_index('ix_glossary_course_term')

    op.drop_table('glossary_terms')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index('ix_users_tenant_email')
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_courses_code'))

    op.drop_table('courses')
    # ### end Alembic commands ###
